openapi: "3.0.0"
info:
  title: MainAPI
  version: 1.0.0
paths:
  /getUserRequests/:
    get:
      summary: Get the userRequets given to the system
      description: Get the userRequets given to the system
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    nic:
                      type: integer
                    name:
                      type: string
                    requestTime:
                      type: dateTime
                    isApproved:
                      type: boolean

        "404":
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  description:
                    type: string

        "500":
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string

      deprecated: false
      security: []

/userRequest/:
  post:
    summary: Post the userRequet given to the system
    description: Post the userRequet given to the system
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              _id:
                type: string
              nic:
                type: integer
              name:
                type: string
              requestTime:
                type: string
              isApproved:
                type: boolean
    responses:
      "200":
        description: OK
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                description:
                  type: string

      "404":
        description: Not found
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                description:
                  type: string

      "500":
        description: Internal Server Error
        content:
          text/plain:
            schema:
              type: string

    deprecated: false
    security: []

  /userRequest/:
    put:
      summary: Update the userRequet given to the system
      description: Update the userRequet given to the system
      parameters:
        - name: id
          in: query
          description: id of the userRequet
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  description:
                    type: string

        "404":
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  description:
                    type: string

        "500":
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string

      deprecated: false
      security: []
